export const placeTypeLabels = {
    "sandwich_shop": "Sandwich-Laden",
    "steak_house": "Steakhaus",
    "mexican_restaurant": "Mexikanisches Restaurant",
    "seafood_restaurant": "Fischrestaurant",
    "ice_cream_shop": "Eisdiele",
    "vegan_restaurant": "Veganes Restaurant",
    "japanese_restaurant": "Japanisches Restaurant",
    "chinese_restaurant": "Chinesisches Restaurant",
    "indian_restaurant": "Indisches Restaurant",
    "thai_restaurant": "Thailändisches Restaurant",
    "french_restaurant": "Französisches Restaurant",
    "italian_restaurant": "Italienisches Restaurant",
    "greek_restaurant": "Griechisches Restaurant",
    "korean_restaurant": "Koreanisches Restaurant",
    "vietnamese_restaurant": "Vietnamesisches Restaurant",
    "coffee_shop": "Café",
    "tea_house": "Teehaus",
    "bakery": "Bäckerei",
    "bar": "Bar",
    "pub": "Kneipe",
    "night_club": "Nachtclub",
    "wine_bar": "Weinbar",
    "brewery": "Brauerei",
    "distillery": "Destillerie",
    "liquor_store": "Spirituosengeschäft",
    "grocery_store": "Lebensmittelgeschäft",
    "supermarket": "Supermarkt",
    "convenience_store": "Kiosk",
    "department_store": "Kaufhaus",
    "clothing_store": "Bekleidungsgeschäft",
    "shoe_store": "Schuhgeschäft",
    "jewelry_store": "Juwelier",
    "book_store": "Buchladen",
    "electronics_store": "Elektronikgeschäft",
    "furniture_store": "Möbelhaus",
    "home_goods_store": "Haushaltswarengeschäft",
    "hardware_store": "Baumarkt",
    "pet_store": "Zoohandlung",
    "toy_store": "Spielwarengeschäft",
    "florist": "Blumenladen",
    "pharmacy": "Apotheke",
    "beauty_salon": "Kosmetiksalon",
    "hair_salon": "Friseursalon",
    "spa": "Wellness-Spa",
    "gym": "Fitnessstudio",
    "yoga_studio": "Yogastudio",
    "tattoo_parlor": "Tattoo-Studio",
    "nail_salon": "Nagelstudio",
    "massage_therapist": "Massagetherapeut",
    "dentist": "Zahnarzt",
    "doctor": "Arzt",
    "hospital": "Krankenhaus",
    "clinic": "Klinik",
    "veterinary_care": "Tierarztpraxis",
    "bank": "Bank",
    "atm": "Geldautomat",
    "post_office": "Postfiliale",
    "police": "Polizeistation",
    "fire_station": "Feuerwache",
    "city_hall": "Rathaus",
    "courthouse": "Gericht",
    "library": "Bibliothek",
    "school": "Schule",
    "university": "Universität",
    "museum": "Museum",
    "art_gallery": "Kunstgalerie",
    "movie_theater": "Kino",
    "amusement_park": "Freizeitpark",
    "zoo": "Zoo",
    "aquarium": "Aquarium",
    "park": "Park",
    "campground": "Campingplatz",
    "rv_park": "Wohnmobilstellplatz",
    "lodging": "Unterkunft",
    "hotel": "Hotel",
    "motel": "Motel",
    "bed_and_breakfast": "Pension",
    "hostel": "Hostel",
    "airport": "Flughafen",
    "train_station": "Bahnhof",
    "subway_station": "U-Bahn-Station",
    "bus_station": "Busbahnhof",
    "taxi_stand": "Taxistand",
    "parking": "Parkplatz",
    "gas_station": "Tankstelle",
    "car_rental": "Autovermietung",
    "car_dealer": "Autohändler",
    "car_repair": "Autowerkstatt",
    "car_wash": "Autowaschanlage",
    "electric_vehicle_charging_station": "Ladestation für Elektrofahrzeuge",
    "moving_company": "Umzugsunternehmen",
    "storage": "Lager",
    "real_estate_agency": "Immobilienagentur",
    "lawyer": "Anwalt",
    "accountant": "Steuerberater",
    "insurance_agency": "Versicherungsagentur",
    "travel_agency": "Reisebüro",
    "funeral_home": "Bestattungsinstitut",
    "church": "Kirche",
    "mosque": "Moschee",
    "synagogue": "Synagoge",
    "hindu_temple": "Hindutempel",
    "buddhist_temple": "Buddhistischer Tempel",
    "cemetery": "Friedhof",
    "embassy": "Botschaft",
    "consulate": "Konsulat",
    "courier_service": "Kurierdienst",
    "dry_cleaner": "Reinigung",
    "laundry": "Waschsalon",
    "locksmith": "Schlüsseldienst",
    "painter": "Maler",
    "plumber": "Klempner",
    "electrician": "Elektriker",
    "roofing_contractor": "Dachdecker",
    "general_contractor": "Bauunternehmen",
    "home_inspector": "Baugutachter",
    "interior_designer": "Innenarchitekt",
    "landscaper": "Landschaftsgärtner",
    "pest_control_service": "Schädlingsbekämpfung",
    "pool_cleaning_service": "Poolreinigungsdienst",
    "security_service": "Sicherheitsdienst",
    "delivery_service": "Lieferservice",
    "shipping_service": "Versanddienst",
    "postal_service": "Postdienst",
    "freight_forwarding_service": "Spedition",
    "logistics_service": "Logistikdienst",
    "transportation_service": "Transportunternehmen",
    "tour_operator": "Reiseveranstalter",
    "cruise_line": "Kreuzfahrtanbieter",
    "bus_company": "Busunternehmen",
    "taxi_service": "Taxidienst",
    "limousine_service": "Limousinenservice",
    "car_service": "Fahrdienst",
    "rideshare_service": "Mitfahrdienst",
    "bicycle_rental_service": "Fahrradverleih",
    "motorcycle_rental_service": "Motorradverleih",
    "scooter_rental_service": "Rollerverleih",
    "boat_rental_service": "Bootsverleih",
    "airline": "Fluggesellschaft",
    "helicopter_service": "Hubschrauberdienst",
    "private_jet_service": "Privatjetservice",
    "space_travel_service": "Weltraumreiseanbieter",
    "tourist_information_center": "Touristeninformation",
    "visitor_center": "Besucherzentrum",
    "information_center": "Informationszentrum",
    "welcome_center": "Willkommenszentrum",
    "convention_center": "Kongresszentrum",
    "exhibition_center": "Messezentrum",
    "conference_center": "Konferenzzentrum",
    "event_venue": "Veranstaltungsort",
    "wedding_venue": "Hochzeitslocation",
    "banquet_hall": "Festsaal",
    "meeting_room": "Tagungsraum",
    "coworking_space": "Coworking Space",
    "business_center": "Business Center",
    "office_space": "Büroräume",
    "virtual_office": "Virtuelles Büro",
    "shared_office": "Geteiltes Büro",
    "executive_suite": "Management-Büro",
    "serviced_office": "Servicebüro",
    "business_incubator": "Gründerzentrum",
    "startup_accelerator": "Startup-Accelerator",
    "technology_park": "Technologiepark",
    "industrial_park": "Industriepark",
    "business_park": "Gewerbepark",
    "science_park": "Wissenschaftspark",
    "research_park": "Forschungscampus",
    "innovation_center": "Innovationszentrum",
    "business_hub": "Business Hub",
    "entrepreneur_center": "Unternehmerzentrum"
  };
  
  export const getPlaceLabel = (type, fallback = "Unbekannter Ort") =>
    placeTypeLabels[type] || fallback;
  
  export default placeTypeLabels;
  